---
name: Feature Request
description: File a feature request.
body:
  - type: markdown
    attributes:
      value: |
        # Important notice regarding filed issues

        This project already fills my needs, and as such I have no real reason to continue it's development. This project is otherwise provided as is, and no support is given.

        If pull requests implementing bug fixes or enhancements are pushed, I am happy to review and merge them (time permitting).

        If you wish to have a feature implemented, you have a few options:

        - Implement it yourself and file a pull request.
        - File an issue and hope someone else implements it for you.
        - Pay me to implement it (my rate is $200 an hour, minimum 1 hour, contact me via my [github email address](https://github.com/josegonzalez) if you want to go this route).

        In all cases, feel free to file an issue, they may be of help to others in the future.
  - type: textarea
    id: what-would-you-like-to-happen
    attributes:
      label: What would you like to happen?
      description: Please describe in detail how the new functionality should work as well as any issues with existing functionality.
    validations:
      required: true
